GET https://api.binance.com/api/v3/ticker/price?symbol=CELOUSDT
Accept: application/json

###
GET https://api.binance.com/api/v3/ticker/price

###
GET https://api.telegram.org/bot5331971662:AAHGlrzp4mWM8IyUyEz25PJaq5Kh7TxOLGQ/getUpdates